GMAIL_USERNAME: masters.tracker@gmail.com
GMAIL_PASSWORD: As34Df56
ADMIN_NAME: masterAdmin
ADMIN_EMAIL: masterAdmin@gmail.com
ADMIN_PASSWORD: masteradmin
ROLES: [admin, developer, tester]
DEFAULT_ROLE: developer
DEFAULT_CLIENT_EMAIL: professorX@mailinator.com
DEFAULT_CLIENT_NAME: ProfessorX